# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6e94a93544cabd1e19131d18eeff9073"
name = "final-chatbot"
application_url = "https://grain-bra-text-tribune.trycloudflare.com"
embedded = true
handle = "final-chatbot"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://grain-bra-text-tribune.trycloudflare.com/auth/callback", "https://grain-bra-text-tribune.trycloudflare.com/auth/shopify/callback", "https://grain-bra-text-tribune.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://grain-bra-text-tribune.trycloudflare.com/apps/chatbot"
subpath = "chatbot"
prefix = "apps"

[pos]
embedded = false
